# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ile_processor.proto\x12\x0e\x66ile_processor\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\xfd\x02\n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12/\n\x0c\x66ile_content\x18\x02 \x01(\x0b\x32\x19.file_processor.FileChunk\x12\x41\n\x13\x63ompress_pdf_params\x18\x03 \x01(\x0b\x32\".file_processor.CompressPDFRequestH\x00\x12\x44\n\x15\x63onvert_to_txt_params\x18\x04 \x01(\x0b\x32#.file_processor.ConvertToTXTRequestH\x00\x12P\n\x1b\x63onvert_image_format_params\x18\x05 \x01(\x0b\x32).file_processor.ConvertImageFormatRequestH\x00\x12\x41\n\x13resize_image_params\x18\x06 \x01(\x0b\x32\".file_processor.ResizeImageRequestH\x00\x42\x0c\n\nparameters\"\x14\n\x12\x43ompressPDFRequest\"\x15\n\x13\x43onvertToTXTRequest\"2\n\x19\x43onvertImageFormatRequest\x12\x15\n\routput_format\x18\x01 \x01(\t\"3\n\x12ResizeImageRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"{\n\x0c\x46ileResponse\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12/\n\x0c\x66ile_content\x18\x02 \x01(\x0b\x32\x19.file_processor.FileChunk\x12\x16\n\x0estatus_message\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32\xd6\x02\n\x14\x46ileProcessorService\x12L\n\x0b\x43ompressPDF\x12\x1b.file_processor.FileRequest\x1a\x1c.file_processor.FileResponse(\x01\x30\x01\x12M\n\x0c\x43onvertToTXT\x12\x1b.file_processor.FileRequest\x1a\x1c.file_processor.FileResponse(\x01\x30\x01\x12S\n\x12\x43onvertImageFormat\x12\x1b.file_processor.FileRequest\x1a\x1c.file_processor.FileResponse(\x01\x30\x01\x12L\n\x0bResizeImage\x12\x1b.file_processor.FileRequest\x1a\x1c.file_processor.FileResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=40
  _globals['_FILECHUNK']._serialized_end=68
  _globals['_FILEREQUEST']._serialized_start=71
  _globals['_FILEREQUEST']._serialized_end=452
  _globals['_COMPRESSPDFREQUEST']._serialized_start=454
  _globals['_COMPRESSPDFREQUEST']._serialized_end=474
  _globals['_CONVERTTOTXTREQUEST']._serialized_start=476
  _globals['_CONVERTTOTXTREQUEST']._serialized_end=497
  _globals['_CONVERTIMAGEFORMATREQUEST']._serialized_start=499
  _globals['_CONVERTIMAGEFORMATREQUEST']._serialized_end=549
  _globals['_RESIZEIMAGEREQUEST']._serialized_start=551
  _globals['_RESIZEIMAGEREQUEST']._serialized_end=602
  _globals['_FILERESPONSE']._serialized_start=604
  _globals['_FILERESPONSE']._serialized_end=727
  _globals['_FILEPROCESSORSERVICE']._serialized_start=730
  _globals['_FILEPROCESSORSERVICE']._serialized_end=1072
# @@protoc_insertion_point(module_scope)
