# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_processor_pb2 as file__processor__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileProcessorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompressPDF = channel.stream_stream(
                '/file_processor.FileProcessorService/CompressPDF',
                request_serializer=file__processor__pb2.FileRequest.SerializeToString,
                response_deserializer=file__processor__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ConvertToTXT = channel.stream_stream(
                '/file_processor.FileProcessorService/ConvertToTXT',
                request_serializer=file__processor__pb2.FileRequest.SerializeToString,
                response_deserializer=file__processor__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ConvertImageFormat = channel.stream_stream(
                '/file_processor.FileProcessorService/ConvertImageFormat',
                request_serializer=file__processor__pb2.FileRequest.SerializeToString,
                response_deserializer=file__processor__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ResizeImage = channel.stream_stream(
                '/file_processor.FileProcessorService/ResizeImage',
                request_serializer=file__processor__pb2.FileRequest.SerializeToString,
                response_deserializer=file__processor__pb2.FileResponse.FromString,
                _registered_method=True)


class FileProcessorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompressPDF(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertToTXT(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertImageFormat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompressPDF': grpc.stream_stream_rpc_method_handler(
                    servicer.CompressPDF,
                    request_deserializer=file__processor__pb2.FileRequest.FromString,
                    response_serializer=file__processor__pb2.FileResponse.SerializeToString,
            ),
            'ConvertToTXT': grpc.stream_stream_rpc_method_handler(
                    servicer.ConvertToTXT,
                    request_deserializer=file__processor__pb2.FileRequest.FromString,
                    response_serializer=file__processor__pb2.FileResponse.SerializeToString,
            ),
            'ConvertImageFormat': grpc.stream_stream_rpc_method_handler(
                    servicer.ConvertImageFormat,
                    request_deserializer=file__processor__pb2.FileRequest.FromString,
                    response_serializer=file__processor__pb2.FileResponse.SerializeToString,
            ),
            'ResizeImage': grpc.stream_stream_rpc_method_handler(
                    servicer.ResizeImage,
                    request_deserializer=file__processor__pb2.FileRequest.FromString,
                    response_serializer=file__processor__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_processor.FileProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('file_processor.FileProcessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileProcessorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompressPDF(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/file_processor.FileProcessorService/CompressPDF',
            file__processor__pb2.FileRequest.SerializeToString,
            file__processor__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertToTXT(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/file_processor.FileProcessorService/ConvertToTXT',
            file__processor__pb2.FileRequest.SerializeToString,
            file__processor__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertImageFormat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/file_processor.FileProcessorService/ConvertImageFormat',
            file__processor__pb2.FileRequest.SerializeToString,
            file__processor__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResizeImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/file_processor.FileProcessorService/ResizeImage',
            file__processor__pb2.FileRequest.SerializeToString,
            file__processor__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
